# Astro Paper - DEV environment
# Image tag di-update otomatis oleh Jenkins pipeline

replicaCount: 1

image:
  repository: harbor.20.44.216.40.nip.io/devsecops/astro-paper
  tag: "9"
  pullPolicy: Always

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app-dev.20.44.216.40.nip.io
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5

env: []
